name: AdvancedTranslateAPI
version: '${project.version}'
main: apa.translateapi.AdvancedTranslateAPI
api-version: '1.19'
authors: [ mrGHOSTWARRIOR ]
description: This plugin allows you to translate your server!